(defpackage "clap.core"
  (:use "CL" "JSON")
  (:export object link))
(in-package "clap.core")

(defclass object ()
  ((attachment :accessor attachment :initarg :attachment)
   (attributedTo :accessor attributedTo :initarg :attributedTo)
   (audience :accessor audience :initarg :audience)
   (content :accessor content :initarg :content
            :initform "https://www.w3e.org/ns/activitystreams")
   (context :accessor context :initarg :context)
   (name :accessor name :initarg :name)
   (end-time :accessor end-time :initarg :end-time)
   (generator :accessor generator :initarg :generator)
   (icon :accessor icon :initarg :icon)
   (image :accessor image :initarg :image)
   (in-reply-to :accessor in-reply-to :initarg :i-reply-to)
   (location :accessor location :initarg :location)
   (preview :accessor preview :initarg :preview)
   (published :accessor preview :initarg :published)
   (replies :accessor replies :initarg :replies)
   (start-time :accessor start-time :initarg :start-time)
   (summary :accessor summary :initarg :summary)
   (tag :accessor tag :initarg :tag)
   (updated :accessor updated :initarg :updated)
   (url :accessor url :initarg :url)
   (to :accessor to :initarg :to)
   (bto :accessor bto :initarg :bto)
   (cc :accessor cc :initarg :cc)
   (bcc :accessor bcc :initarg :bcc)
   (media-type :accessor media-type :initarg :media-type)
   (duration :accessor duration :initarg :duration)
   (object-type :reader object-type :initform "Object"
                :allocation :class)))

(defclass link ()
  ((href :accessor href :initarg :href)
   (rel :initarg :rel :accessor rel)
   (media-type :accessor media-type :initarg :media-type)
   (name :accessor name :initarg :name)
   (hreflang :accessor hreflang :initarg :hreflang :initform "en")
   (height :accessor height :initarg :height)
   (width :accessor width :initarg :width)
   (preview :accessor preview :initarg :preview)
   (object-type :reader object-type :initform "Link"
                :allocation :class)))

