(in-package :clap-entities)

(defclass application (ap-object)
  ((object-type :reader object-type :initform "Application")))
(defclass person (ap-object)
  ((object-type :reader object-type :initform "Person")))
(defclass group (ap-object)
  ((object-type :reader object-type :initform "Group")))
(defclass organization (ap-object)
  ((object-type :reader object-type :initform "Organization")))
