(in-package :clap-entities)

(defclass application (ap-object) ()
  (:metaclass json-serializable-class))
(defclass person (ap-object) ()
  (:metaclass json-serializable-class))
(defclass group (ap-object) ()
  (:metaclass json-serializable-class))
(defclass organization (ap-object) ()
  (:metaclass json-serializable-class))
