(in-package :clap-entities)

(defclass relationship (ap-object)
  ((relationship-subject :accessor relationship-subject
                         :initarg :relationship-subject)
   (relationship-object :accessor relationship-object
                        :initarg :relationship-object)))

(defclass article (ap-object) ())
(defclass audio (ap-object) ())
(defclass document (ap-object) ())
(defclass image (ap-object) ())
(defclass video (ap-object) ())
(defclass note (ap-object) ())
(defclass page (document) ())
(defclass event (ap-object) ())
(defclass place (ap-object)
  ((accuracy :accessor accuracy :initarg :accuracy)
   (altitude :accessor altitude :initarg :altitude)
   (latitude :accessor latitude :initarg :latitude)
   (longitude :accessor longitude :initarg :longitude)
   (radius :accessor radius :initarg :radius)
   (units :accessor units :initarg :units)))
(defclass profile (ap-object)
  ((describes :accessor describes :initarg :describes)))
(defclass tombstone (ap-object)
  ((former-type :accessor former-type :initarg :former-type)
   (deleted :accessor deleted :initarg :deleted)))

(defclass mention (link) ())
